### ISSUE TITLE
Notification not working in android 4.4.2 version

### ISSUE THREAD

**Issue by brahmikumar** [phonegap-build/PushPlugin#425]
I am trying in implementing push notification in my application. Notification working properly up to android 4.3.0 version devices. But in android 4.3.0, when i install app, app not open getting unfortunately application name has stopped. 

I'm getting errors in logcat as.

02-13 17:49:13.765: E/AndroidRuntime(13286): FATAL EXCEPTION: IntentService[GCMIntentService-GCMIntentService-1]
02-13 17:49:13.765: E/AndroidRuntime(13286): java.lang.RuntimeException: java.lang.Throwable: Warning: A WebView method was called on thread 'IntentService[GCMIntentService-GCMIntentService-1]'. All WebView methods must be called on the UI thread. Future versions of WebView may not support use on other threads.
02-13 17:49:13.765: E/AndroidRuntime(13286):    at android.webkit.WebView.checkThread(WebView.java:1974)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at android.webkit.WebView.loadUrl(WebView.java:804)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at org.apache.cordova.CordovaWebView.loadUrlNow(CordovaWebView.java:439)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at org.apache.cordova.CordovaWebView.loadUrl(CordovaWebView.java:341)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at com.plugin.gcm.PushPlugin.sendJavascript(PushPlugin.java:105)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at com.plugin.gcm.GCMIntentService.onRegistered(GCMIntentService.java:43)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at com.google.android.gcm.GCMBaseIntentService.handleRegistration(GCMBaseIntentService.java:296)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at com.google.android.gcm.GCMBaseIntentService.onHandleIntent(GCMBaseIntentService.java:197)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at android.os.Handler.dispatchMessage(Handler.java:99)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at android.os.Looper.loop(Looper.java:137)
02-13 17:49:13.765: E/AndroidRuntime(13286):    at android.os.HandlerThread.run(HandlerThread.java:61)
02-13 17:49:13.765: E/AndroidRuntime(13286): Caused by: java.lang.Throwable: Warning: A WebView method was called on thread 'IntentService[GCMIntentService-GCMIntentService-1]'. All WebView methods must be called on the UI thread. Future versions of WebView may not support use on other threads.
02-13 17:49:13.765: E/AndroidRuntime(13286):    at android.webkit.WebView.checkThread(WebView.java:1965)
02-13 17:49:13.765: E/AndroidRuntime(13286):    ... 11 more
02-13 17:49:13.795: D/CordovaActivity(13286): Paused the application!
02-13 17:49:13.795: D/CordovaWebView(13286): Handle the pause
02-13 17:49:13.975: D/CordovaLog(13286): file:///android_asset/www/my.js: Line 632 : Received Event: f5db548f8f6110a0831bf65924059acd
02-13 17:49:13.975: I/Web Console(13286): Received Event: f5db548f8f6110a0831bf65924059acd at file:///android_asset/www/my.js:632

**Comment by hiperlouro** [comment]
I too had this problem when developing in Android 5.1.
After investigating a while, I've come to the conclusion that I needed to change the sendjavascript function in PushPlugin.java to this:

	/*
	 * Sends a json object to the client as parameter to a method which is defined in gECB.
	 */
	public static void sendJavascript(JSONObject _json) {
		final String _d = "javascript:" + gECB + "(" + _json.toString() + ");";
		Log.v(TAG, "sendJavascript: " + _d);
		if (gECB != null && gWebView != null) {
            
            // Get the main thread and load the URL there.
            // Use loadUrl instead of sendjavascript because it is deprecated
            Handler mainHandler = new Handler(Looper.getMainLooper());
            mainHandler.post(new Runnable() {
                @Override
                public void run() {
                    gWebView.loadUrl(_d);
                }
            });
        }
	}
