### ISSUE TITLE
Plugin incompatible in Android: https://github.com/Wizcorp/phonegap-facebook-plugin.git

### ISSUE THREAD

**Issue by danicastanos** [phonegap-build/PushPlugin#556]
When the two plugins are added to the project in Android this error is shown (in iOS works perfectly):
exec] UNEXPECTED TOP-LEVEL EXCEPTION:
[exec] com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
[exec] at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
[exec] at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
[exec] at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
[exec] at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
[exec] at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
[exec] at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
[exec] at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
[exec] at com.android.dx.command.dexer.Main.run(Main.java:246)
[exec] at com.android.dx.command.dexer.Main.main(Main.java:215)
[exec] at com.android.dx.command.Main.main(Main.java:106)
[exec]
[exec] :dexRelease FAILED
[exec]
[exec] BUILD FAILED
[exec]
[exec] Total time: 30.975 secs
[exec]
[exec] FAILURE: Build failed with an exception.
[exec]
[exec] * What went wrong:
[exec] Execution failed for task ':dexRelease'.
[exec] > com.android.ide.common.internal.LoggedErrorException: Failed to run command:
[exec] /Users/danicastanos/Library/Android/sdk/build-tools/22.0.1/dx --dex --output /Users/danicastanos/Documents/koala/app/platforms/android/build/intermediates/dex/release --input-list=/Users/danicastanos/Documents/koala/app/platforms/android/build/intermediates/tmp/dex/release/inputList.txt
[exec] Error Code:
[exec] 2
[exec] Output:
[exec]
[exec] UNEXPECTED TOP-LEVEL EXCEPTION:
[exec] com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;
[exec] at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
[exec] at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
[exec] at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
[exec] at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
[exec] at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
[exec] at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
[exec] at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
[exec] at com.android.dx.command.dexer.Main.run(Main.java:246)
[exec] at com.android.dx.command.dexer.Main.main(Main.java:215)
[exec] at com.android.dx.command.Main.main(Main.java:106)
[exec]
[exec]
[exec]
[exec] * Try:
[exec] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
[exec] ERROR building one of the platforms: Error: /Users/danicastanos/Documents/koala/app/platforms/android/cordova/build: Command failed with exit code 8
[exec] You may not have the required environment or OS to build this project
[exec]
[exec] /Users/danicastanos/Documents/koala/app/platforms/android/cordova/node_modules/q/q.js:126
[exec] throw e;
[exec] ^
[exec] Error code 1 for command: /Users/danicastanos/Documents/koala/app/platforms/android/gradlew with args: cdvBuildRelease,-b,/Users/danicastanos/Documents/koala/app/platforms/android/build.gradle,-Dorg.gradle.daemon=true
[exec] Error: /Users/danicastanos/Documents/koala/app/platforms/android/cordova/build: Command failed with exit code 8
[exec] at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:131:23)
[exec] at ChildProcess.emit (events.js:98:17)
[exec] at maybeClose (child_process.js:766:16)
[exec] at Process.ChildProcess._handle.onexit (child_process.js:833:5)

**Comment by alpjor** [comment]
We found the fix in this thread:
https://github.com/Wizcorp/phonegap-facebook-plugin/pull/1032

The issue is that two versions of the android-support library are being included.
