### ISSUE TITLE
Unable to build for android after installing this plugin

### ISSUE THREAD

**Issue by Dineshrajaa** [phonegap-build/PushPlugin#594]
Hello,
 I am using this plugin for getting push-notification in my app and its working well if I take a build from build.phonegap.com service but its failing to build for android when I compile it locally using cordova-cli with this error.Kindly help me to fix this issue.

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
        at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
        at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
        at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
        at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
        at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
        at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
        at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
        at com.android.dx.command.dexer.Main.run(Main.java:246)
        at com.android.dx.command.dexer.Main.main(Main.java:215)
        at com.android.dx.command.Main.main(Main.java:106)

:dexDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
        /opt/android-sdk/build-tools/22.0.1/dx --dex --no-optimize --output /home/dinesh/Development/Mywork/SoConnected/platforms/android/build/intermediates/dex/debug --input-list=/home/dinesh/Development/Mywork/SoConnected/platforms/android/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
        2
  Output:
  
        UNEXPECTED TOP-LEVEL EXCEPTION:
        com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompatIcs;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
                at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
                at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)

**Comment by Ziv-Barber** [comment]
Add:

configurations {
	all*.exclude group: 'com.android.support', module: 'support-v4'
}

To your build.gradle file in the platforms/android folder.

**Comment by Dineshrajaa** [comment]
Thanks for the response after modifying  the build.gradle file I could build it using CLI and install it in the device but I couldn't start the plugin usage (i.e.,Push notification code is not working).

**Comment by barryvdh** [comment]
I had to add that line to the gradle file, but also copy `android-support-v4.jar` from `android-sdk\extras\android\support\v4` to `platforms/android/libs`. I don't know if that's normal?

**Comment by NNA** [comment]
I also had a build problem after adding PushPlugin
```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Landroid/support/v4/app/NotificationCompatHoneycomb;
```
Modifying the build.gradle file as suggested by @Ziv-Barber worked like a charm

Thanks :+1:

**Comment by jonasribeiroc** [comment]
I had same problem, in my case was the phonegap-facebook-plugin, and I added the 'configurations' than my buddy Ziv-Barber supposed to me, thanks Ziv-Barber. And sorry for my english.

**Comment by thomasvbe** [comment]
That doesn't help for me, or I misplace it? Any other options? Thx!

**Comment by globaltalentgrid** [comment]
Ziv-Barber! You are a rockstar!
This solved the issue.
