### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Qnalo** [phonegap-build/PushPlugin#610]
Hi,
    We tried to install Pushplugin  using.
1.cordova plugin add https://github.com/phonegap-build/PushPlugin.git
Fetching plugin "https://github.com/phonegap-build/PushPlugin.git" via git clone
We tried to install in new project as well as old projects.

Installing "com.phonegap.plugins.PushPlugin" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.phonegap.plugins.PushPlugin':Error: Uh oh!
ENOENT, no such file or directory 'C:\cordova\push\platforms\android\local.prope
rties'
    at Object.fs.openSync (fs.js:427:18)
    at Object.fs.readFileSync (fs.js:284:15)

**Comment by cwoolum** [comment]
I'm getting an error trying to add as well

Fetching plugin "https://github.com/phonegap-build/PushPlugin.git" via git clone

Repository "https://github.com/phonegap-build/PushPlugin.git" checked out to git
 ref "master".
Installing "com.phonegap.plugins.PushPlugin" for android
Error during processing of action! Attempting to revert...
Failed to install 'com.phonegap.plugins.PushPlugin':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.win32.resolve (path.js:146:13)
    at Object.module.exports.framework.install (C:\Users\slick\AppData\Roaming\n
pm\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.j
s:139:35)
    at installWrapper (C:\Users\slick\AppData\Roaming\npm\node_modules\cordova\n
ode_modules\cordova-lib\src\platforms\platforms.js:77:32)
    at Object.ActionStack.process (C:\Users\slick\AppData\Roaming\npm\node_modul
es\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:68:25)
    at handleInstall (C:\Users\slick\AppData\Roaming\npm\node_modules\cordova\no
de_modules\cordova-lib\src\plugman\install.js:550:20)
    at C:\Users\slick\AppData\Roaming\npm\node_modules\cordova\node_modules\cord
ova-lib\src\plugman\install.js:342:28

**Comment by ayajshaikh** [comment]
Same Error

Installing "com.phonegap.plugins.PushPlugin" for android

Error during processing of action! Attempting to revert...

Failed to install 'com.phonegap.plugins.PushPlugin':TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at module.exports.framework.install (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:106:31)
    at Object.ActionStack.process (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:108:17)

TypeError: Uh oh!
Arguments to path.resolve must be strings
    at Object.exports.resolve (path.js:313:15)
    at module.exports.framework.install (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/android.js:106:31)
    at Object.ActionStack.process (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:72:25)
    at handleInstall (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:591:20)
    at /usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:340:28
    at _fulfilled (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:787:54)
    at self.promiseDispatch.done (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:816:30)
    at Promise.promise.promiseDispatch (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:749:13)
    at /usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:509:49
    at flush (/usr/local/lib/node_modules/phonegap/node_modules/cordova/node_modules/q/q.js:108:17)

**Comment by cwoolum** [comment]
I ended up using `cordova plugin add https://github.com/phonegap-build/PushPlugin.git#2.4.0` to get the lastest working tag instead of HEAD

**Comment by Qnalo** [comment]
It is not even installing using #2.4.0

**Comment by cwoolum** [comment]
Make sure you uninstall the plugin before trying to install 2.4.0

**Comment by Qnalo** [comment]
There is some problem in this plugin.
From last 15 minutes it is showing.
Fetching plugin "https://github.com/phonegap-build/PushPlugin.git" via git clone.
Though internet speed is good.

**Comment by jongkwang** [comment]
@cwoolum , Thank you so much.
It work very well with your method
```
cordova plugin remove com.phonegap.plugins.PushPlugin
cordova plugin add https://github.com/phonegap-build/PushPlugin.git#2.4.0
```

**Comment by Qnalo** [comment]
It is installed but unable to receive push notification.
Send Push message  through PHP and java.But not receiving on test app.
The success message recieved as follows .
MulticastResult(multicast_id=############29####,total=1,success=1,failure=0,canonical_ids=0,results: [[ messageId=0:########## ]]

**Comment by cwoolum** [comment]
I was able to successfully receive messages on Android 5.1.1. I think there
are some other bugs related to messages not showing up properly. Make sure
the message you sent is in the correct format.

**Comment by theaccordance** [comment]
Classic example of why dependency management works best when you can explicitly declare your versions

**Comment by amirudin** [comment]
+1 
Release 2.5.0 incompatible with PhoneGap Build for Android as well. Most probably caused by https://github.com/phonegap-build/PushPlugin/pull/588

**Comment by sicter** [comment]
+1
v2.4.0 worked for me

**Comment by JessPG** [comment]
@cwoolum thank you, now it's working.

**Comment by jdinse** [comment]
+1
Same with XDK Build for Android. Version 2.4.0 worked.

**Comment by velniukas** [comment]
+1 
2.4.0 worked

**Comment by leonardoalemax** [comment]
+1 
2.4.0 worked

**Comment by chetanporiya** [comment]
+1
Worked for me as well.

**Comment by TonyExpress** [comment]
To install last version (it's recommended, why would you install a version already obsolete?) probably you should update cordova and android platform, and then uninstall and reinstall the plugin:

sudo npm update -g cordova
cordova platform update android

and finally uninstall and reinstall the plugin

**Comment by jcuervo** [comment]
@tonyhef's suggestion worked fine for me. thanks, bro!

**Comment by rclatorre** [comment]
Thanks, this worked for me in Intel XDK

Make sure you uninstall the plugin before trying to install 2.4.0

**Comment by cwoolum** [comment]
It seems this plugin is deprecated... I might be better to use the new one vs installing the deprecated version above

https://github.com/phonegap/phonegap-plugin-push

**Comment by JonathanNasc** [comment]
I'm having this problem with the new version 1.4.0
https://github.com/phonegap/phonegap-plugin-push

[edit] I was using the cordova version 3.6.3, when I updated it works well.

**Comment by jackvial** [comment]
+1 
2.4.0 worked

**Comment by bandhavya** [comment]
https://github.com/phonegap-build/PushPlugin.git#2.4.0 throws error.

![image](https://cloud.githubusercontent.com/assets/12510202/12701293/ff9073cc-c82a-11e5-99dc-aafc3463e275.png)

**Comment by QuipHop** [comment]
+1 
2.4.0 installed
thanks

**Comment by 19akash91** [comment]
I am having same problem and i have all try in top suggestions

Error: Failed to fetch plugin https://github.com/phonegap-build/PushPlugin.git via git.
Either there is a connection problems, or plugin spec is incorrect:
        Error: "git" command line tool is not installed: make sure it is accessible on your PATH.

**Comment by cwoolum** [comment]
@19akash91 your issue looks unrelated to this. It looks like Git is not installed correctly on your machine

**Comment by 19akash91** [comment]
my problem is solved after reinstall Git

@cwoolum Thank you sir
