### ISSUE TITLE
Visual Studio 2015 Cordova - MdaVsCli -- FAILED

### ISSUE THREAD

**Issue by k0tel** [phonegap-build/PushPlugin#628]
Hi, when I created empty project and add PushPlugin via "plugin wizard" and build application get this error:

Beginning processing of action stack for android project... (TaskId:23)
1>  Parsing android project files... (TaskId:23)
1>  Installing Android library: com.android.support:support-v4:+ (TaskId:23)
1>  Error during processing of action! Attempting to revert... (TaskId:23)
1>  Failed to install 'com.phonegap.plugins.PushPlugin':TypeError Uh oh! (TaskId:23)
1>  Arguments to path.resolve must be strings (TaskId:23)
1>      at Object.win32.resolve (path.js:146:13) (TaskId:23)
1>      at module.exports.framework.install (C:\Users\matej_000\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\platforms\android.js:139:35) (TaskId:23)
1>      at Object.ActionStack.process (C:\Users\matej_000\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\util\action-stack.js:67:25) (TaskId:23)
1>      at handleInstall (C:\Users\matej_000\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:575:20) (TaskId:23)
1>      at C:\Users\matej_000\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\cordova-lib\src\plugman\install.js:335:28 (TaskId:23)
1>      at _fulfilled (C:\Users\matej_000\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:787:54) (TaskId:23)
1>      at self.promiseDispatch.done (C:\Users\matej_000\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:816:30) (TaskId:23)
1>      at Promise.promise.promiseDispatch (C:\Users\matej_000\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:749:13) (TaskId:23)
1>      at C:\Users\matej_000\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:509:49 (TaskId:23)
1>      at flush (C:\Users\matej_000\AppData\Roaming\npm\node_modules\vs-tac\node_modules\cordova\4.3.1\node_modules\cordova\node_modules\q\q.js:108:17) (TaskId:23)
1>  TypeError: Uh oh! (TaskId:23)
1>  Arguments to path.resolve must be strings (TaskId:23)
1>Done executing task "MdaVsCli" -- FAILED. (TaskId:23)
1>Done building target "PrepareForRippleRequirements" in project "Application.jsproj" -- FAILED.: (TargetId:20)

Please help me :(

**Comment by idanbezalel** [comment]
Did you deployed to android device (developer enabled) or to emulator ?

**Comment by joaolori** [comment]
Im getting thiis error too...
Im using real android device, compile project before add plugin, get error after add plugin.
I have update my cordova version to 5.5.1 and still get error
1>  FAILURE: Build failed with an exception.
1>  
1>  * What went wrong:
1>  A problem occurred configuring root project 'android'.
1>  > Could not resolve all dependencies for configuration ':_debugCompile'.
1>     > Could not find any version that matches com.android.support:support-v4:+
1>  .
1>       Searched in the following locations:
1>           https://repo1.maven.org/maven2/com/android/support/support-v4/maven-
1>  metadata.xml
1>           https://repo1.maven.org/maven2/com/android/support/support-v4/
1>       Required by:
1>           :android:unspecified
1>  
1>  * Try:
1>  Run with --stacktrace option to get the stack trace. Run with --info or --deb
1>  ug option to get more log output.
1>  
1>  BUILD FAILED
1>  
1>  Total time: 5.599 secs
1>  
1>  C:\Users\JP\Desktop\Wallet.App\WalletApp\bld\Debug\platforms\android\cordova\
1>  node_modules\q\q.js:126
1>                      throw e;
1>                            ^
1>  Error code 1 for command: cmd with args: /s /c "C:\Users\JP\Desktop\Wallet.Ap
1>  p\WalletApp\bld\Debug\platforms\android\gradlew cdvBuildDebug -b C:\Users\JP\
1>  Desktop\Wallet.App\WalletApp\bld\Debug\platforms\android\build.gradle -Dorg.g
1>  radle.daemon=true"
1>  Command finished with error code 8: cmd /s /c "C:\Users\JP\Desktop\Wallet.App
1>  \WalletApp\bld\Debug\platforms\android\cordova\build.bat --debug  "
1>MDAVSCLI : error : cmd: Command failed with exit code 8
1>Done executing task "MdaVsCli" -- FAILED.
1>Done building target "BuildMDA" in project "WalletApp.jsproj" -- FAILED.
1>
1>Build FAILED.
1>
1>Time Elapsed 00:00:19.82
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by joaolori** [comment]
Another thing, this already worked for me, but now after updated the version of plugin and cordova that dont work anymore... pls help

**Comment by idanbezalel** [comment]
after installing the plugin 2.5.0 version , the cordova project not compiled , it cant find the plugin , 
im using vs2013 update 4 , cordova tools 3.1 . 
in Clean cordova  project  that compiles and deployed before installing the plugin .

**Comment by joaolori** [comment]
Ok, i have updated ADB Support Library Android and everthing goes ok

**Comment by idanbezalel** [comment]
how do I update it in my environment  ?

**Comment by joaolori** [comment]
U need to update via Android SDK manager localted at program files / android
